version: '2'

services:

  http:
    container_name: healthy_http
    build:
      context: ./
    environment:
      HEALTHY_LOG_LEVEL: info
      HEALTHY_PORT: 80
      HEALTHY_MANAGEMENT_PORT: 3280
#      HEALTHY_CONFIG_FILE: example.yaml
      HEALTHY_CONFIG_YAML: |
        version: 1
        name: Simple example
        groups:
          - name: Simple
            validate:
              - name: Success
                type: simple
                args:
                  - status: success
    ports:
      - 80:80
#      - 3280:3280
