version: '2'

services:
  healthy:
    image: spyzhov/healthy:latest
    environment:
      HEALTHY_LOG_LEVEL: info
      HEALTHY_PORT: 80
      HEALTHY_MANAGEMENT_PORT: 3280
      HEALTHY_CONFIG_FILE: /app/example.yaml
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret-password
      POSTGRES_DB: example
    volumes:
    - ./:/app:ro
    ports:
      - 80:80
#      - 3280:3280
  postgres:
    image: postgres:11-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret-password
      POSTGRES_DB: example
